import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import fs from 'fs';
import path from 'path';

const processedTocFilePath = path.join(__dirname, 'docs', 'api', 'toc_processed.json');
const toc = JSON.parse(fs.readFileSync(processedTocFilePath, 'utf8'));

const sidebars: SidebarsConfig = {
    // apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
    apiSidebar: toc.apiSidebar,
    // apiSidebar: [{type: 'autogenerated', dirName: './api'}],
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
};

export default sidebars;