import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import fs from 'fs';
import path from 'path';

const processedTocFilePath = path.join(__dirname, 'content', 'api', 'toc_processed.json');

let apiSidebar = [];
try {
    if (fs.existsSync(processedTocFilePath)) {
        const toc = JSON.parse(fs.readFileSync(processedTocFilePath, 'utf8'));
        apiSidebar = toc.apiSidebar;
    } else {
        console.warn('Warning: toc_processed.json file not found. Using empty API sidebar.');
    }
} catch (error) {
    console.error('Error loading API sidebar:', error);
}

const sidebars: SidebarsConfig = {
    // Only include apiSidebar if it has content
    ...(apiSidebar.length > 0 && { apiSidebar }),
    architectureSidebar: [{ type: 'autogenerated', dirName: 'architecture' }],
    gameDesignSidebar: [{ type: 'autogenerated', dirName: 'game_design' }],
    tutorialsSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
};

export default sidebars;