name: Build Docs and Deploy to Firebase

on:
  #   push:
  #     branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    name: Build and Deploy Documentation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build API Documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docfx.json

      - name: Process API Files
        run: npm run process-api
        working-directory: docs

      - name: Install Packages in Docs Folder
        run: npm install
        working-directory: docs

      - name: Build Documentation
        run: npm run build
        working-directory: docs

      - name: Encrypt Built Docs
        run: staticrypt build -r
        working-directory: docs
        env:
          STATICRYPT_PASSWORD: ${{ secrets.STATICRYPT_PASSWORD }}

      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: ${{ github.ref_name == 'main' && 'live' || github.ref_name }}
          expires: ${{ github.ref_name == 'dev' && '30d' || '7d' }}
          entryPoint: docs/encrypted/build
