name: Build Docs and Deploy to Firebase

on:
  #   push:
  #     branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    name: Build and Deploy Documentation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
            fetch-depth: 0 # Fetch all history so we can set up sparse-checkout
    
      - name: Set up sparse-checkout
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set docs
      
      - name: Checkout 'docs' Folder
        run: git checkout

    #   - name: Build API Documentation
    #     uses: nikeee/docfx-action@v1.0.0
    #     with:
    #       args: docfx.json

      - name: List Directories
        run: ls -l

      - name: List Directories on Docs Folder
        run: ls -l docs

    #   - name: Change Directory to Root
    #     run: cd ..

      - name: Install Packages in docs Folder
        run: npm install
        working-directory: docs

      - name: Process API Files
        run: npm run process-api
        working-directory: docs
        
      - name: Build Documentation
        run: npm run build
        working-directory: docs

      - name: Encrypt Built Docs
        run: npx staticrypt build -r
        env:
          STATICRYPT_PASSWORD: ${{ secrets.STATICRYPT_PASSWORD }}
        working-directory: docs

      - name: List Directories on docs Folder
        run: ls -l docs

      - name: Deploy to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          channelId: ${{ github.ref_name == 'main' && 'live' || github.ref_name }}
          expires: ${{ github.ref_name == 'dev' && '30d' || '7d' }}
          entryPoint: docs

    outputs:
        url: ${{ steps.deploy.outputs.details_url }}