name: Build Docs and Deploy to Github Pages

on:
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Documentation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Directories
        run: ls -l

      - name: List Directories on docs/ Folder
        run: ls -l docs

      - name: Install Packages in docs Folder
        run: npm install
        working-directory: docs

      - name: Process API Files
        run: npm run process-api
        working-directory: docs

      - name: Build Documentation
        run: npm run build
        working-directory: docs

      - name: Encrypt Built Docs
        run: npx staticrypt build -r
        env:
          STATICRYPT_PASSWORD: ${{ secrets.STATICRYPT_PASSWORD }}
        working-directory: docs

      - name: List Directories on docs Folder
        run: ls -l docs

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/build

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4